### ISSUE TITLE
shape_predictor_68_face_landmarks.dat

### ISSUE THREAD

**Issue by deepsurbhi8** [Neha13022020/Syncnet_model_VIDTIMIT_dataset#3]
Hi, the link for the mentioned file is shown on your drive. Can you please tell me from where to get the above file?

**Comment by Neha13022020** [comment]
https://www.dropbox.com/sh/5ecqtwuy85nlonb/AAAP6_YLa5cA1P_s5sJV3d-5a?dl=0
